---
# This Playbook implements a rolling update on the infrastructure, change the value of the serial keyword to specify the number of servers the update should happen.

- name: Remove the code from server
  command: rm -rf /var/www/html/*

- name: disable the server in Netscaler
  local_action: netscaler_control nsc_host=${ns_host} user=${ns_user} password=${ns_password} name=service-HTTP-${ansible_hostname} type=service action=disable

- name: Copy the code from repository
  git: repo=${repository} dest=/var/www/html/
   
- name: Create's the index.php file
  template: src=../roles/web/templates/index.php.j2 dest=/var/www/html/index.php

- name: enable the server in Netscaler
  local_action: netscaler_control nsc_host=${ns_host} user=${ns_user} password=${ns_password} name=service-HTTP-${ansible_hostname} type=service action=enable

