---
# This playbook contains common plays that would be run on all Nodes.

- name: Install ntp 
  yum: name=ntp state=present
  tags: ntp

- name: Configure ntp file
  template: src=../roles/common/templates/ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=true
  tags: ntp

- name: Download the EPEL repository RPM
  get_url: url=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm dest=/tmp/ force=yes

- name: Install EPEL RPM
#  command: rpm -Uvh --force /tmp/epel-release-6-8.noarch.rpm
  yum: name=/tmp/epel-release-6-8.noarch.rpm state=installed

- name: Clean up
  command: rm -f /tmp/epel-release-6-8.noarch.rpm
